### PR TITLE
bg-color-fixed

### PR DESCRIPTION
**Pull request by SamarendraGouda**
First of all sorry, as I fixed the issue #23 without it being assigned to me!

I have added a line (line 152)  in the NavBar.jsx file.
`background : rgb(12,51,52,1);
`

I am attaching screenshots of before and after the fix:

Before:
Screenshot from 2023-04-14 14-58-07

After:
Screenshot from 2023-04-14 14-58-14

Hope this helps!

### CODE REVIEW

**Comment by martinyis** [comment]
@SamarendraGouda .Thank you for your pr. There are some issues that need to be fixed For Contributing MD it should be styled accordingly to .md format. Bullets, sections, links, etc.

**Comment by SamarendraGouda** [comment]
Yeah I'll be working on that issue, i raised this PR for issue #23. Will be raising another one for the Contributing.md file once it is completed.

**Comment by SamarendraGouda** [comment]
Hey @martinyis,
I have updated the CONTRIBUTING.md file. Do check it out!

**Comment by martinyis** [comment]
> Hey @martinyis, I have updated the CONTRIBUTING.md file. Do check it out!

Thanks for contributing, I am merging this!

**Pull request merged**
